---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01ezfhae126pz9nynx26bydx0c"
    - from: "jfevt@*"
      to: "jfevt@01ezfha4frb4q00nh5xqp613j2"
    - from: "jfmd@*"
      to: "jfmd@01ezfhaehakhc23s8yknmdceje"
    - from: "jfrt@*"
      to: "jfrt@01ezfhb3454qre0a6ghkyb1e7a"
    - from: "jffe@*"
      to: "jffe@000"
licenses:
- server-name: "fa0976009a2d"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlPRlF4Tmpvd09Eb3lNeTR3TmpCYUNtbGtPaUF6TkdGa05HTTBOaTFsWlRobExUUmlaREV0\r\
    \nWVRFMU9TMWlNV013TjJVeVpXVXhOV0VLYjNkdVpYSTZJRWxqYjI0Z1RVeEZDbkJ5YjNCbGNuUnBa\r\
    \nWE02SUh0OUNuTnBaMjVoZEhWeVpUb2diblZzYkFwMGNtbGhiRG9nZEhKMVpRcDBlWEJsT2lCVVVr\r\
    \nbEJUQXAyWVd4cFpFWnliMjA2SURJd01qRXRNREl0TWpaVU1UWTZNRGc2TWpNdU1EWXdXZ289CiAg\r\
    \nICBzaWduYXR1cmU6IGtHNnBhYkdxN0F3UW5QNGpWZlZxVHdEOGdldUE4S3diYVpyZFNaakVRNnZk\r\
    \nQk5iekJlM0E1enZZTzlTc3BGbzBsOW5hSjR2VEpyOUlObENralhHZmxKTHNzdHV2eUI5b3FtQ2Iw\r\
    \nYTRUdGJsMTJVT2FHeklQSDZ1d200WHFEVDkzUzZwVTlCT0JFNDRUOWVWSmFzcUFScnlZNDUwOG80\r\
    \neklaY1AyL0tkTXF5dWtSRk02Y2JlVzJIRjU1NEp3QStwaGpxWmYrZ2Jaa3NMdEN6MTFKQ1R4bEJ3\r\
    \nS2liQ29nYjdmb3hTTS9kWUh5N3dZWG5pbTcxVXU4UEdMWE8wcjZQNWg5UkloTTE2aWhVUGluRW5C\r\
    \ndTQwUFREUU1aOUwvQW5oRlNDeldIR0FnK3RPTlU4YnVXWFhtZ2R6eVJFeEpMUXREN21Na25xZ0V1\r\
    \nWVRZeFI3cmloRlRaQT09CnZlcnNpb246IDEK\r\n"
- server-name: "f345f20191b6"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlPRlF4Tmpvd09Eb3lNeTR3TmpCYUNtbGtPaUF6TkdGa05HTTBOaTFsWlRobExUUmlaREV0\r\
    \nWVRFMU9TMWlNV013TjJVeVpXVXhOV0VLYjNkdVpYSTZJRWxqYjI0Z1RVeEZDbkJ5YjNCbGNuUnBa\r\
    \nWE02SUh0OUNuTnBaMjVoZEhWeVpUb2diblZzYkFwMGNtbGhiRG9nZEhKMVpRcDBlWEJsT2lCVVVr\r\
    \nbEJUQXAyWVd4cFpFWnliMjA2SURJd01qRXRNREl0TWpaVU1UWTZNRGc2TWpNdU1EWXdXZ289CiAg\r\
    \nICBzaWduYXR1cmU6IGtHNnBhYkdxN0F3UW5QNGpWZlZxVHdEOGdldUE4S3diYVpyZFNaakVRNnZk\r\
    \nQk5iekJlM0E1enZZTzlTc3BGbzBsOW5hSjR2VEpyOUlObENralhHZmxKTHNzdHV2eUI5b3FtQ2Iw\r\
    \nYTRUdGJsMTJVT2FHeklQSDZ1d200WHFEVDkzUzZwVTlCT0JFNDRUOWVWSmFzcUFScnlZNDUwOG80\r\
    \neklaY1AyL0tkTXF5dWtSRk02Y2JlVzJIRjU1NEp3QStwaGpxWmYrZ2Jaa3NMdEN6MTFKQ1R4bEJ3\r\
    \nS2liQ29nYjdmb3hTTS9kWUh5N3dZWG5pbTcxVXU4UEdMWE8wcjZQNWg5UkloTTE2aWhVUGluRW5C\r\
    \ndTQwUFREUU1aOUwvQW5oRlNDeldIR0FnK3RPTlU4YnVXWFhtZ2R6eVJFeEpMUXREN21Na25xZ0V1\r\
    \nWVRZeFI3cmloRlRaQT09CnZlcnNpb246IDEK\r\n"
- server-name: "3b872bfc1ea1"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlPRlF4Tmpvd09Eb3lNeTR3TmpCYUNtbGtPaUF6TkdGa05HTTBOaTFsWlRobExUUmlaREV0\r\
    \nWVRFMU9TMWlNV013TjJVeVpXVXhOV0VLYjNkdVpYSTZJRWxqYjI0Z1RVeEZDbkJ5YjNCbGNuUnBa\r\
    \nWE02SUh0OUNuTnBaMjVoZEhWeVpUb2diblZzYkFwMGNtbGhiRG9nZEhKMVpRcDBlWEJsT2lCVVVr\r\
    \nbEJUQXAyWVd4cFpFWnliMjA2SURJd01qRXRNREl0TWpaVU1UWTZNRGc2TWpNdU1EWXdXZ289CiAg\r\
    \nICBzaWduYXR1cmU6IGtHNnBhYkdxN0F3UW5QNGpWZlZxVHdEOGdldUE4S3diYVpyZFNaakVRNnZk\r\
    \nQk5iekJlM0E1enZZTzlTc3BGbzBsOW5hSjR2VEpyOUlObENralhHZmxKTHNzdHV2eUI5b3FtQ2Iw\r\
    \nYTRUdGJsMTJVT2FHeklQSDZ1d200WHFEVDkzUzZwVTlCT0JFNDRUOWVWSmFzcUFScnlZNDUwOG80\r\
    \neklaY1AyL0tkTXF5dWtSRk02Y2JlVzJIRjU1NEp3QStwaGpxWmYrZ2Jaa3NMdEN6MTFKQ1R4bEJ3\r\
    \nS2liQ29nYjdmb3hTTS9kWUh5N3dZWG5pbTcxVXU4UEdMWE8wcjZQNWg5UkloTTE2aWhVUGluRW5C\r\
    \ndTQwUFREUU1aOUwvQW5oRlNDeldIR0FnK3RPTlU4YnVXWFhtZ2R6eVJFeEpMUXREN21Na25xZ0V1\r\
    \nWVRZeFI3cmloRlRaQT09CnZlcnNpb246IDEK\r\n"
- server-name: "db9b8cb111b2"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlPRlF4Tmpvd09Eb3lNeTR3TmpCYUNtbGtPaUF6TkdGa05HTTBOaTFsWlRobExUUmlaREV0\r\
    \nWVRFMU9TMWlNV013TjJVeVpXVXhOV0VLYjNkdVpYSTZJRWxqYjI0Z1RVeEZDbkJ5YjNCbGNuUnBa\r\
    \nWE02SUh0OUNuTnBaMjVoZEhWeVpUb2diblZzYkFwMGNtbGhiRG9nZEhKMVpRcDBlWEJsT2lCVVVr\r\
    \nbEJUQXAyWVd4cFpFWnliMjA2SURJd01qRXRNREl0TWpaVU1UWTZNRGc2TWpNdU1EWXdXZ289CiAg\r\
    \nICBzaWduYXR1cmU6IGtHNnBhYkdxN0F3UW5QNGpWZlZxVHdEOGdldUE4S3diYVpyZFNaakVRNnZk\r\
    \nQk5iekJlM0E1enZZTzlTc3BGbzBsOW5hSjR2VEpyOUlObENralhHZmxKTHNzdHV2eUI5b3FtQ2Iw\r\
    \nYTRUdGJsMTJVT2FHeklQSDZ1d200WHFEVDkzUzZwVTlCT0JFNDRUOWVWSmFzcUFScnlZNDUwOG80\r\
    \neklaY1AyL0tkTXF5dWtSRk02Y2JlVzJIRjU1NEp3QStwaGpxWmYrZ2Jaa3NMdEN6MTFKQ1R4bEJ3\r\
    \nS2liQ29nYjdmb3hTTS9kWUh5N3dZWG5pbTcxVXU4UEdMWE8wcjZQNWg5UkloTTE2aWhVUGluRW5C\r\
    \ndTQwUFREUU1aOUwvQW5oRlNDeldIR0FnK3RPTlU4YnVXWFhtZ2R6eVJFeEpMUXREN21Na25xZ0V1\r\
    \nWVRZeFI3cmloRlRaQT09CnZlcnNpb246IDEK\r\n"
- server-name: "d24c97694a7a"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd015MHlPRlF4Tmpvd09Eb3lNeTR3TmpCYUNtbGtPaUF6TkdGa05HTTBOaTFsWlRobExUUmlaREV0\r\
    \nWVRFMU9TMWlNV013TjJVeVpXVXhOV0VLYjNkdVpYSTZJRWxqYjI0Z1RVeEZDbkJ5YjNCbGNuUnBa\r\
    \nWE02SUh0OUNuTnBaMjVoZEhWeVpUb2diblZzYkFwMGNtbGhiRG9nZEhKMVpRcDBlWEJsT2lCVVVr\r\
    \nbEJUQXAyWVd4cFpFWnliMjA2SURJd01qRXRNREl0TWpaVU1UWTZNRGc2TWpNdU1EWXdXZ289CiAg\r\
    \nICBzaWduYXR1cmU6IGtHNnBhYkdxN0F3UW5QNGpWZlZxVHdEOGdldUE4S3diYVpyZFNaakVRNnZk\r\
    \nQk5iekJlM0E1enZZTzlTc3BGbzBsOW5hSjR2VEpyOUlObENralhHZmxKTHNzdHV2eUI5b3FtQ2Iw\r\
    \nYTRUdGJsMTJVT2FHeklQSDZ1d200WHFEVDkzUzZwVTlCT0JFNDRUOWVWSmFzcUFScnlZNDUwOG80\r\
    \neklaY1AyL0tkTXF5dWtSRk02Y2JlVzJIRjU1NEp3QStwaGpxWmYrZ2Jaa3NMdEN6MTFKQ1R4bEJ3\r\
    \nS2liQ29nYjdmb3hTTS9kWUh5N3dZWG5pbTcxVXU4UEdMWE8wcjZQNWg5UkloTTE2aWhVUGluRW5C\r\
    \ndTQwUFREUU1aOUwvQW5oRlNDeldIR0FnK3RPTlU4YnVXWFhtZ2R6eVJFeEpMUXREN21Na25xZ0V1\r\
    \nWVRZeFI3cmloRlRaQT09CnZlcnNpb246IDEK\r\n"
schema-version: 2
